Progress tracking bar
WomenPlusPlus/deploy-impact-23-kpi-3 pull request #106
Opened 2023-10-25 15:45 UTC by biancam5

-creating progress bar component 
- as requested created a sum function that sum every value of the month and show this value on the progress bar (i used a text endpoint so the values are a bit high because the endpoint has high values  however this would  change  .  )
- story of progress bar

2023-10-25 16:06 UTC, maalej requested changes

2023-10-25 16:06 UTC, maalej commented on src/components/dataviz/ProgressBar.tsx
> +  data?: any;
the data here is label or target, no?

2023-10-25 16:06 UTC, maalej commented on src/components/dataviz/ProgressBar.tsx
> +      {data && <h5 style={{ textAlign: 'center', marginTop: 8, marginRight: 160, fontWeight: 'normal' }} >{data}</h5>}
1. use flexbox
2. use https://ant.design/components/typography

2023-10-25 16:58 UTC, biancam5 commented on src/components/dataviz/ProgressBar.tsx
> +  data?: any;
The data is target, as requested on the task

2023-10-27 11:20 UTC, maalej approved these changes

2023-10-27 11:23 UTC, merged